t = int(input('Digite um número para ver sua tabuada: '))
print('____________')
print(f'1 x {t} = {t*1}')
print(f'2 x {t} = {t*2}')
print(f'3 x {t} = {t*3}')
print(f'4 x {t} = {t*4}')
print(f'5 x {t} = {t*5}')
print(f'6 x {t} = {t*6}')
print(f'7 x {t} = {t*7}')
print(f'8 x {t} = {t*8}')
print(f'9 x {t} = {t*9}')
print(f'10 x {t} = {t*10}')
print('____________')